### ISSUE TITLE
Update adobe.github.com/data/server.json

### ISSUE THREAD

**Issue by jarkkosyrjala** [adobe/adobe.github.com#53]
adobe.github.com/data/server.json needs to be updated, because data is outdated.
"1 year 5 months since last commit"
![adobe github io-screen shot 2016-05-03 at 10 30 01](https://cloud.githubusercontent.com/assets/1029627/14977124/398957e6-111a-11e6-9c00-83c3487d8923.png)

**Comment by kimchouard** [comment]
Interesting... It shows "20h..." on my side.

![adobe_open_source___advancing_technology_through_open_initiatives](https://cloud.githubusercontent.com/assets/2856923/15002225/d045122c-1153-11e6-9ff7-9a330e3d0eeb.png)

Did you full refreshed the page? (Ctrl+Maj+R) What browser are you using?

Thanks for the issue filing though!

**Comment by jarkkosyrjala** [comment]
It seems that request to http://server-adobe-github.herokuapp.com/ fails and and outdated json from adobe.github.com/data/server.json is loaded instead (as a backup?) when browsing using HTTPS protocol. 

https://adobe.github.io/ "1 year 5 months since last commit"
http://adobe.github.io/ "3 h 38 min since last commit"
