### ISSUE TITLE
Adobe Logo looks blurred

### ISSUE THREAD

**Issue by codlocker** [adobe/adobe.github.com#59]
Hi,
The Adobe Logo on the left-hand side of the website looks blurred in Chrome(Version 54). In Mozilla it looks ok but the text size of "Adobe" is pretty small. The issue is very small. I mentioned it since it is on the home page. The image is from Chrome.
![capture image](https://cloud.githubusercontent.com/assets/12949012/20856742/f0e121b0-b93c-11e6-910b-0c1300e1356e.png)

Thank you

**Comment by noraacl** [comment]
@codlocker thanks for reporting this; will look into it.
