### ISSUE TITLE
Site not loading due to server issues

### ISSUE THREAD

**Issue by stevengill** [adobe/adobe.github.com#69]
Server repo is at https://github.com/adobe/server.adobe.github.com.

List of orgs has changed (some have been deleted). Thus causing issues with the server not sending a response and the site hanging. 

We don't have access to the heroku instance that server is running on. So will have to
* fix the broken code in server.adobe.github.com
* deploy our own instance
* update this site to use the new instance

**Comment by stevengill** [comment]
Actually, looks like the server just pulls the orgs from https://github.com/adobe/adobe.github.com/blob/master/data/org.json. So updating this file should fix the problems

**Comment by stevengill** [comment]
I removed the dead orgs, but it hasn't solved the problem :(. I wonder if the server needs to be restarted.

**Comment by stevengill** [comment]
Looks like the server is down. Here is where it is referenced. https://github.com/adobe/adobe.github.com/commit/63bec3ff644546c439933930a606a6bafa06796e

Here is why I think it is down. http://server-adobe-github.herokuapp.com/

**Comment by macdonst** [comment]
@stevengill can we just re-write the server portion as Runtime actions? I would totally do that and blog about it. That way we don't need to run the service on heroku anymore.

**Comment by filmaj** [comment]
Such a great idea @macdonst !

The whole site needs a facelift, redesign, rethink... BURN IT DOWN, START OVER I SAY!

**Comment by stevengill** [comment]
So looks like it is back up now. I think my fix from yesterday did it. The server must have auto restarted at some point. Closing this issue!
