### ISSUE TITLE
The site not loading completely

### ISSUE THREAD

**Issue by vinhkhuc** [adobe/adobe.github.com#76]
The sections "Statistics", "Repos" and "Organizations" are not loading. I think that happens because the site http://server-adobe-github.herokuapp.com/ is down.

Probably, it's related to the issue #69.

**Comment by stevengill** [comment]
Thanks for reporting this @vinhkhuc!

I ended up launching a new server at https://opensource-adobe-server.herokuapp.com/. Now the site points to that one.
