### ISSUE TITLE
Styling issue with Navbar

### ISSUE THREAD

**Issue by harshcut** [adobe/adobe.github.com#88]
## Description

Height of `.menu` is `50px` and content overflow is visible, which creates a uneven shape at the bottom of navbar.

## Current behavior

![adobe-nav-issue-curr](https://user-images.githubusercontent.com/66206863/92555240-d1f01b00-f284-11ea-9e3b-ca4815bded7c.png)

## Expected Output

![adobe-nav-issue-exp](https://user-images.githubusercontent.com/66206863/92555258-dfa5a080-f284-11ea-9286-936281aa99bc.png)

**Comment by macdonst** [comment]
Merged and deployed fix
