### ISSUE TITLE
Footer github logo not fixed

### ISSUE THREAD

**Issue by Ritwik880** [adobe/adobe.github.com#90]
![Screenshot (297)](https://user-images.githubusercontent.com/54446880/94252182-32e44800-ff41-11ea-92c7-c06a72bfe6d1.png)

**Comment by kishore007k** [comment]
I would love to work on this. Can you assign me? @Ritwik880

**Comment by macdonst** [comment]
The way the github logo is just peaking above the fold is an intentional design choice.
