### ISSUE TITLE
Web page not opening

### ISSUE THREAD

**Issue by srijanishere** [adobe/adobe.github.com#98]
The web page is not opening on Microsoft Edge Version 93.0.961.38

**Comment by yugalmittal05** [comment]
which web page is not opening, can you tell me?

**Comment by srijanishere** [comment]
opensource.adobe.com : this one is not opening

**Comment by yugalmittal05** [comment]
> The web page is not opening on Microsoft Edge Version 93.0.961.38

plz update your browser and then open it. its works.

**Comment by srijanishere** [comment]
Okay, sure.
